// AUTOGENERATED — DO NOT EDIT. Source: ~/.claude/memory/whatsapp_tokens.json
import Foundation

enum WaIcons {
    static let cdnBase = "https://d1dlwtcfl0db67.cloudfront.net/icons"

    static let lock_12 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-lock-12.svg")!
    static let disappearing_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-disappearing-16.svg")!
    static let pin_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-pin-16.svg")!
    static let archived_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-archived-24.svg")!
    static let plus_filter_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-plus-filter-24.svg")!
    static let meetball_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-meetball-24.svg")!
    static let camera_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-camera-24.svg")!
    static let plus_add_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-plus-add-24.svg")!
    static let search_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-search-24.svg")!
    static let check_read_19 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-check-read-19.svg")!
    static let check_sent_19 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-check-sent-19.svg")!
    static let voice_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-voice-16.svg")!
    static let deleted_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-deleted-16.svg")!
    static let location_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-location-16.svg")!
    static let group_16 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-group-16.svg")!
    static let tab_updates_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-tab-updates-32.svg")!
    static let tab_calls_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-tab-calls-32.svg")!
    static let tab_communities_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-tab-communities-32.svg")!
    static let tab_chats_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-tab-chats-32.svg")!
    static let tab_settings_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-tab-settings-32.svg")!
    static let meta_ai_circle = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-meta-ai-circle.svg")!
    static let updates_ring_full = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-full.svg")!
    static let updates_ring_right = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-right.svg")!
    static let updates_ring_left = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-left.svg")!
    static let updates_ring_top = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-top.svg")!
    static let updates_ring_bottom = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-bottom.svg")!
    static let updates_ring_quarter = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-updates-ring-quarter.svg")!
    static let status_cellular = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-status-cellular.svg")!
    static let status_wifi = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-status-wifi.svg")!
    static let status_battery = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-status-battery.svg")!
    static let chevron_lt_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-chevron-lt-32.svg")!
    static let video_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-video-32.svg")!
    static let phone_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-phone-32.svg")!
    static let plus_input_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-plus-input-32.svg")!
    static let sticker_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-sticker-24.svg")!
    static let camera_small_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-camera-small-32.svg")!
    static let mic_32 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-mic-32.svg")!
    static let bubble_tail = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-bubble-tail.svg")!
    static let bubble_tail_mask = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-bubble-tail-mask.svg")!
    static let bubble_tail_fill = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-bubble-tail-fill.svg")!
    static let check_bubble_17 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-check-bubble-17.svg")!
    static let close_circular_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-close-circular-24.svg")!
    static let send_24 = URL(string: "https://d1dlwtcfl0db67.cloudfront.net/icons/ic-wa-send-24.svg")!
}
