// AUTOGENERATED — DO NOT EDIT. Source: ~/.claude/memory/whatsapp_tokens.json
import SwiftUI

struct WhatsAppColors {
    let surfacePrimary: Color
    let surfaceProduct: Color
    let surfaceCtaFilters: Color
    let surfaceCtaFiltersActive: Color
    let surfaceCtaCircular: Color
    let surfacePanelBlur: Color
    let surfacePanel: Color
    let surfaceSearchChat: Color
    let surfaceInvert: Color
    let surfaceBaloonMe: Color
    let surfaceBaloonOther: Color
    let surfaceDate: Color
    let surfaceInputChat: Color
    let surfaceShadowBaloon: Color
    let textPrimary: Color
    let textSecondary: Color
    let textSecondaryAlpha: Color
    let textProduct: Color
    let textInvert: Color
    let textCtaFilters: Color
    let textCtaFiltersActive: Color
    let textTabbar: Color
    let textTabbarSelected: Color
    let borderPanel: Color
    let borderSeparator: Color
    let borderAvatar: Color
    let borderInputChat: Color
    let borderQuote: Color
    let textQuoteTitle: Color

    static let light = WhatsAppColors(
        surfacePrimary: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        surfaceProduct: Color(red: 0.114, green: 0.671, blue: 0.380, opacity: 1),
        surfaceCtaFilters: Color(red: 0.957, green: 0.957, blue: 0.957, opacity: 1),
        surfaceCtaFiltersActive: Color(red: 0.816, green: 0.996, blue: 0.812, opacity: 1),
        surfaceCtaCircular: Color(red: 0.039, green: 0.039, blue: 0.039, opacity: 0.03),
        surfacePanelBlur: Color(red: 0.957, green: 0.957, blue: 0.957, opacity: 0.8),
        surfacePanel: Color(red: 0.961, green: 0.949, blue: 0.922, opacity: 0.8),
        surfaceSearchChat: Color(red: 0.957, green: 0.957, blue: 0.957, opacity: 1),
        surfaceInvert: Color(red: 0.039, green: 0.039, blue: 0.039, opacity: 1),
        surfaceBaloonMe: Color(red: 0.816, green: 0.996, blue: 0.812, opacity: 1),
        surfaceBaloonOther: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        surfaceDate: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        surfaceInputChat: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        surfaceShadowBaloon: Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.06),
        textPrimary: Color(red: 0.039, green: 0.039, blue: 0.039, opacity: 1),
        textSecondary: Color(red: 0.463, green: 0.467, blue: 0.475, opacity: 1),
        textSecondaryAlpha: Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.5),
        textProduct: Color(red: 0.114, green: 0.671, blue: 0.380, opacity: 1),
        textInvert: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        textCtaFilters: Color(red: 0.463, green: 0.467, blue: 0.475, opacity: 1),
        textCtaFiltersActive: Color(red: 0.082, green: 0.376, blue: 0.243, opacity: 1),
        textTabbar: Color(red: 0.463, green: 0.467, blue: 0.475, opacity: 1),
        textTabbarSelected: Color(red: 0.039, green: 0.039, blue: 0.039, opacity: 1),
        borderPanel: Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.3),
        borderSeparator: Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.2),
        borderAvatar: Color(red: 0.039, green: 0.039, blue: 0.039, opacity: 0.1),
        borderInputChat: Color(red: 0.698, green: 0.698, blue: 0.698, opacity: 1),
        borderQuote: Color(red: 0.831, green: 0.165, blue: 0.400, opacity: 1),
        textQuoteTitle: Color(red: 0.831, green: 0.165, blue: 0.400, opacity: 1)
    )

    static let dark = WhatsAppColors(
        surfacePrimary: Color(red: 0.043, green: 0.078, blue: 0.102, opacity: 1),
        surfaceProduct: Color(red: 0.114, green: 0.671, blue: 0.380, opacity: 1),
        surfaceCtaFilters: Color(red: 0.122, green: 0.173, blue: 0.200, opacity: 1),
        surfaceCtaFiltersActive: Color(red: 0.043, green: 0.212, blue: 0.141, opacity: 1),
        surfaceCtaCircular: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.08),
        surfacePanelBlur: Color(red: 0.067, green: 0.106, blue: 0.129, opacity: 0.8),
        surfacePanel: Color(red: 0.067, green: 0.106, blue: 0.129, opacity: 0.85),
        surfaceSearchChat: Color(red: 0.122, green: 0.173, blue: 0.200, opacity: 1),
        surfaceInvert: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 1),
        surfaceBaloonMe: Color(red: 0.000, green: 0.361, blue: 0.294, opacity: 1),
        surfaceBaloonOther: Color(red: 0.125, green: 0.173, blue: 0.200, opacity: 1),
        surfaceDate: Color(red: 0.122, green: 0.173, blue: 0.200, opacity: 1),
        surfaceInputChat: Color(red: 0.122, green: 0.173, blue: 0.200, opacity: 1),
        surfaceShadowBaloon: Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.2),
        textPrimary: Color(red: 0.914, green: 0.929, blue: 0.937, opacity: 1),
        textSecondary: Color(red: 0.525, green: 0.588, blue: 0.627, opacity: 1),
        textSecondaryAlpha: Color(red: 0.914, green: 0.929, blue: 0.937, opacity: 0.5),
        textProduct: Color(red: 0.145, green: 0.827, blue: 0.400, opacity: 1),
        textInvert: Color(red: 0.043, green: 0.078, blue: 0.102, opacity: 1),
        textCtaFilters: Color(red: 0.525, green: 0.588, blue: 0.627, opacity: 1),
        textCtaFiltersActive: Color(red: 0.686, green: 0.949, blue: 0.749, opacity: 1),
        textTabbar: Color(red: 0.525, green: 0.588, blue: 0.627, opacity: 1),
        textTabbarSelected: Color(red: 0.914, green: 0.929, blue: 0.937, opacity: 1),
        borderPanel: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.12),
        borderSeparator: Color(red: 0.525, green: 0.588, blue: 0.627, opacity: 0.2),
        borderAvatar: Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.08),
        borderInputChat: Color(red: 0.196, green: 0.239, blue: 0.267, opacity: 1),
        borderQuote: Color(red: 0.949, green: 0.380, blue: 0.588, opacity: 1),
        textQuoteTitle: Color(red: 0.949, green: 0.380, blue: 0.588, opacity: 1)
    )
}

private struct WhatsAppColorsKey: EnvironmentKey {
    static let defaultValue: WhatsAppColors = .light
}

extension EnvironmentValues {
    var whatsAppColors: WhatsAppColors {
        get { self[WhatsAppColorsKey.self] }
        set { self[WhatsAppColorsKey.self] = newValue }
    }
}
